sudo: false

addons:
  apt:
    packages:
      - libgmp-dev
      - oracle-java8-installer
      - oracle-java8-set-default

env:
 # - GHCVER=7.6.3  ESVER=1.6.0 # Deprecated
 # - GHCVER=7.8.3  ESVER=1.0.3 # Deprecated
 # - GHCVER=7.8.3  ESVER=1.1.2 # Deprecated
 # - GHCVER=7.8  ESVER=1.2.4 # deprecated
 - GHCVER=7.8  ESVER=1.3.6 ESFLAG=ES1 DLINK=https://download.elastic.co/elasticsearch/elasticsearch/elasticsearch
 - GHCVER=7.8  ESVER=1.4.1 ESFLAG=ES1 DLINK=https://download.elastic.co/elasticsearch/elasticsearch/elasticsearch
 - GHCVER=7.10 ESVER=1.5.2 ESFLAG=ES1 DLINK=https://download.elastic.co/elasticsearch/elasticsearch/elasticsearch
 - GHCVER=7.10 ESVER=1.6.0 ESFLAG=ES1 DLINK=https://download.elastic.co/elasticsearch/elasticsearch/elasticsearch
 - GHCVER=7.10 ESVER=1.7.2 ESFLAG=ES1 DLINK=https://download.elastic.co/elasticsearch/elasticsearch/elasticsearch
 - GHCVER=8.0  ESVER=1.7.2 ESFLAG=ES1 DLINK=https://download.elastic.co/elasticsearch/elasticsearch/elasticsearch
 - GHCVER=8.0  ESVER=5.0.2 ESFLAG=ES5 DLINK=https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch

install:
  # stack
  - export STACK_YAML=stack-$GHCVER.yaml
  - mkdir -p ~/.local/bin
  - travis_retry curl -L https://github.com/commercialhaskell/stack/releases/download/v1.2.0/stack-1.2.0-linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  - export PATH=~/.local/bin:$PATH
  - stack --version

  # elasticsearch
  - wget --no-check-certificate $DLINK-$ESVER.tar.gz
  - tar xzf elasticsearch-$ESVER.tar.gz
  # set up a repo for snapshot testing. Required in ES >= 1.6
  - echo "path.repo = [\"/tmp\"]" >> ./elasticsearch-$ESVER/elasticsearch.yml
  - ./elasticsearch-$ESVER/bin/elasticsearch &

script:
  - stack setup
  - stack update
  - stack build
  - stack test --flag bloodhound:$ESFLAG

cache:
  directories:
  - $HOME/.stack
