flags: {}
packages:
- '.'
extra-deps:
- aeson-0.10.0.0
- attoparsec-0.13.0.1
- time-1.5.0.1
- doctest-0.10.1
- doctest-prop-0.2.0.1
- quickcheck-properties-0.1
- uri-bytestring-0.1.9
resolver: lts-2.18
